### ISSUE TITLE
结果返回正常，能运行，但会报一个错

### ISSUE THREAD

**Issue by liuchaowen** [flmn/aly_oss#4]
AlyOss: 8217de6b-624b-4eb2-a7c3-e81ebb2554e3
W/System.err( 6431): android.os.NetworkOnMainThreadException
W/System.err( 6431): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
W/System.err( 6431): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
W/System.err( 6431): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
W/System.err( 6431): 	at java.net.InetAddress.getByName(InetAddress.java:1106)
W/System.err( 6431): 	at com.alibaba.sdk.android.oss.common.utils.OSSUtils.isValidateIP(OSSUtils.java:795)
W/System.err( 6431): 	at com.alibaba.sdk.android.oss.OSSImpl.<init>(OSSImpl.java:133)
W/System.err( 6431): 	at com.alibaba.sdk.android.oss.OSSClient.<init>(OSSClient.java:116)
W/System.err( 6431): 	at tech.jitao.aly_oss.MethodCallHandlerImpl.init(MethodCallHandlerImpl.java:98)
W/System.err( 6431): 	at tech.jitao.aly_oss.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:46)
W/System.err( 6431): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
W/System.err( 6431): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
W/System.err( 6431): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
W/System.err( 6431): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 6431): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err( 6431): 	at android.os.Looper.loop(Looper.java:174)
W/System.err( 6431): 	at android.app.ActivityThread.main(ActivityThread.java:7695)
W/System.err( 6431): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 6431): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
W/System.err( 6431): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
I/flutter ( 6431): oss=========={instanceId: 8217de6b-624b-4eb2-a7c3-e81ebb2554e3, requestId: a99036bb-39bb-4ed1-8f1e-9ff34f2e190f}
I/flutter ( 6431): {success: true}

**Comment by liuchaowen** [comment]
> AlyOss: 8217de6b-624b-4eb2-a7c3-e81ebb2554e3
> W/System.err( 6431): android.os.NetworkOnMainThreadException
> W/System.err( 6431): at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
> W/System.err( 6431): at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
> W/System.err( 6431): at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
> W/System.err( 6431): at java.net.InetAddress.getByName(InetAddress.java:1106)
> W/System.err( 6431): at com.alibaba.sdk.android.oss.common.utils.OSSUtils.isValidateIP(OSSUtils.java:795)
> W/System.err( 6431): at com.alibaba.sdk.android.oss.OSSImpl.(OSSImpl.java:133)
> W/System.err( 6431): at com.alibaba.sdk.android.oss.OSSClient.(OSSClient.java:116)
> W/System.err( 6431): at tech.jitao.aly_oss.MethodCallHandlerImpl.init(MethodCallHandlerImpl.java:98)
> W/System.err( 6431): at tech.jitao.aly_oss.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:46)
> W/System.err( 6431): at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
> W/System.err( 6431): at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
> W/System.err( 6431): at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
> W/System.err( 6431): at android.os.MessageQueue.nativePollOnce(Native Method)
> W/System.err( 6431): at android.os.MessageQueue.next(MessageQueue.java:336)
> W/System.err( 6431): at android.os.Looper.loop(Looper.java:174)
> W/System.err( 6431): at android.app.ActivityThread.main(ActivityThread.java:7695)
> W/System.err( 6431): at java.lang.reflect.Method.invoke(Native Method)
> W/System.err( 6431): at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:516)
> W/System.err( 6431): at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:950)
> I/flutter ( 6431): oss=========={instanceId: 8217de6b-624b-4eb2-a7c3-e81ebb2554e3, requestId: a99036bb-39bb-4ed1-8f1e-9ff34f2e190f}
> I/flutter ( 6431): {success: true}
